name: 'Restore npm cache'
description: 'Restore npm dependencies from cache'
inputs:
    cache-prefix:
        description: 'Cache prefix (change to invalidate)'
        default: 'npm-deps-v1'
        required: false
runs:
    using: composite
    steps:
        - name: Restore npm cache
          uses: actions/cache@v4
          with:
              path: |
                  ~/.npm
                  ./node_modules
              key: ${{ runner.os }}-${{ inputs.cache-prefix }}-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                  ${{ runner.os }}-${{ inputs.cache-prefix }}-
