name: Sync readme/assets to WordPress.org

on:
    push:
        branches:
            - master

jobs:
    update:
        name: Update WordPress.org readme & assets
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Sync to WordPress.org SVN
              uses: 10up/action-wordpress-plugin-asset-update@stable
              env:
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SLUG: popup-maker
                  ASSETS_DIR: .wordpress-org
