name: PHPCS Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]
    paths:
      - "**.php"
      - ".phpcs.dist.xml"
      - ".github/workflows/phpcs-tests.yml"
  workflow_dispatch:

jobs:
  phpcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # important!

    - name: Remove composer.lock
      run: rm composer.lock

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPCS tests
      uses: thenabeel/action-phpcs@v8
      with:
        files: "**.php" # you may customize glob as needed
        phpcs_path: vendor/bin/phpcs
        standard: .phpcs.dist.xml